### ISSUE TITLE
testEchoMessagePrivmsg flakes a bit

### ISSUE THREAD

**Issue by slingamn** [DanielOaks/irctest#8]
````
======================================================================
FAIL: testEchoMessagePrivmsg (test_echo_message.EchoMessageTestCase)
        <http://ircv3.net/specs/extensions/echo-message-3.2.html>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/shivaram/workspace/irctest/irctest/cases.py", line 430, in newf
    return f(self)
  File "/data/shivaram/workspace/irctest/irctest/server_tests/test_echo_message.py", line 73, in f
    extra_format=(m1, m2))
  File "/data/shivaram/workspace/irctest/irctest/cases.py", line 83, in assertEqual
    super().assertEqual(got, expects, fail_msg)
AssertionError: {'time': '2017-11-14T04:45:38.603Z'} != {'time': '2017-11-14T04:45:38.604Z'}
- {'time': '2017-11-14T04:45:38.603Z'}
?                                 ^

+ {'time': '2017-11-14T04:45:38.604Z'}
?                                 ^
 : Tags of forwarded and echoed messages differ: Message(tags={'time': '2017-11-14T04:45:38.603Z'}, prefix='baz!~f@127.0.0.1', command='PRIVMSG', params=['#chan', 'hello everyone']) Message(tags={'time': '2017-11-14T04:45:38.604Z'}, prefix='baz!~f@127.0.0.1', command='PRIVMSG', params=['#chan', 'hello everyone'])
````

**Comment by DanielOaks** [comment]
...that test is silly. expecting the times to be identical to like the nanosecond doesn't make sense. we can rip that comparison test out tbh.

**Comment by DanielOaks** [comment]
9824bb22960b6809970e04a5c8ad3b1d88989651 should fix this properly
